import type { Metadata } from "next";
import './globals.scss'
import  "bootstrap/dist/css/bootstrap.min.css"
import HeaderMenu from "./ui/headerMenu";
import InputSearch from "./ui/inputSearch";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <HeaderMenu/>
        <div className="row justify-content-center">
          <InputSearch/>
        </div>
        {children}
      </body>
    </html>
  );
}
